---
title: "10_bilingual"
output: html_document
date: "2024-08-27"
---

```{r, eval=TRUE}
con <- connect_to_peekbank(db_version = "workshop_2024_dev")
all_aoi_timepoints <- get_aoi_timepoints(connection = con, rle=FALSE)

# reload connection in case it is stale
con <- connect_to_peekbank(db_version = "workshop_2024_dev")
all_stimuli <- collect(get_stimuli(connection = con))
all_administrations <- collect(get_administrations(connection = con))
all_subjects <- unpack_aux_data(collect(get_subjects(connection = con)))
all_trial_types <- collect(get_trial_types(connection = con))
all_trials <- unpack_aux_data(collect(get_trials(connection = con)))
all_datasets <- get_datasets(connection=con) %>% collect()
```

Parse out Bilingual and Monolingual subjects

```{r}

exp_subjects <- all_subjects %>% unnest(subject_aux_data) %>% unnest(lang_exposures) %>% select(subject_id, native_language, exposure)

bilingual_subjects <- exp_subjects %>% group_by(subject_id, native_language) %>% summarise(exposure = sum(exposure)) %>% filter(exposure < 100) %>% mutate(exposure = 100-exposure) %>% bind_rows(exp_subjects)

bilingual_subjects <- bilingual_subjects %>% group_by(subject_id, native_language) %>% summarise(st_exp = sd(exposure), min_exp = ifelse(min(exposure)<=50,min(exposure),100-min(exposure))) %>% ungroup() %>% mutate(bilingual = ifelse(native_language %in% c("spa, eng","eng, fre")| min_exp %in% seq(9,51),TRUE,FALSE)) %>% select(subject_id, bilingual, st_exp, min_exp) %>% distinct()

all_subjects <- all_subjects %>% left_join(bilingual_subjects)


```

Get vanilla data

```{r}
aoi_data_joined <- all_aoi_timepoints |>
  right_join(all_administrations) |>
  right_join(all_subjects) |>
  right_join(all_trials) |>
  right_join(all_trial_types) |>
  mutate(stimulus_id = target_id) |>
  left_join(all_stimuli) |>
  select(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id, 
         stimulus_id, distractor_id, t_norm, age, aoi, full_phrase_language, english_stimulus_label, 
         stimulus_novelty, target_side, vanilla_trial, bilingual) %>%
  rename(target_label = english_stimulus_label, 
         target_id = stimulus_id,
         trial_language = full_phrase_language) %>%
  left_join(all_stimuli %>%
              select(stimulus_id, dataset_id, 
                     stimulus_novelty, english_stimulus_label) %>%
              rename(distractor_id = stimulus_id, 
                     distractor_novelty = stimulus_novelty,
                     distractor_label = english_stimulus_label))

d_joined <- aoi_data_joined |>
  filter(!(dataset_name %in% c("casillas_tseltal_2015", 
                               "hurtado_2008", 
                               "kartushina_2019",
                               "weisleder_stl",
                               "xsectional_2007",
                               "garrison_bergelson_2020", 
                               "moore_bergelson_2022_verb"))) |>
  filter(age <= 60, 
         vanilla_trial == TRUE,
         stimulus_novelty == "familiar",
         distractor_novelty == "familiar") |> 
  select(dataset_name, subject_id, administration_id, trial_id, trial_order,
         dataset_id, target_id, t_norm, age, aoi, trial_language, target_label, distractor_label, target_side, bilingual) |>
  mutate(correct = ifelse(aoi == "target", 1, 
                          ifelse(aoi == "distractor", 0, NA)), 
         target_label = str_to_lower(target_label),
         distractor_label = str_to_lower(distractor_label))
```


# Reaction Time 

```{r}
source(here::here("helper/rt_helper.R"))
```

```{r}
#reformat data
rt_data <- d_joined %>%
  filter(any(t_norm == 0), # must have data at 0
         t_norm >= 0) %>% # only pass data after 0
  group_by(subject_id, administration_id, trial_id) %>%
  summarise(lengths = rle(aoi)$lengths, 
            values = rle(aoi)$values) #run-length-encoded format expected

# compute RTs
rts <- rt_data %>%
  group_by(subject_id, administration_id, trial_id) %>%
  nest() %>%
  mutate(data = lapply(data, get_rt)) %>% 
  unnest(cols = c(data)) %>%
  left_join(d_joined %>%
              select(-t_norm, -correct, -aoi) %>%
              distinct())

```

## Reaction Time density plots and histograms

```{r}

ggplot(filter(rts, shift_type %in% c("T-D", "D-T")), 
       aes(x = rt, fill = shift_type)) + 
  # geom_histogram() + 
  geom_density(alpha = .5) + 
  facet_wrap(~bilingual)

ggplot(filter(rts, shift_type %in% c("T-D", "D-T"),trial_language=="eng"), 
       aes(x = rt, fill = shift_type)) + 
  # geom_histogram() + 
  geom_density(alpha = .5) + 
  facet_wrap(~bilingual)

ggplot(filter(rts, shift_type %in% c("T-D", "D-T"),trial_language=="eng"), 
       aes(x = rt, fill = shift_type)) + 
  # geom_histogram() + 
  geom_density(alpha = .5) + 
  facet_wrap(~bilingual)

ggplot(filter(rts, shift_type %in% c("T-D", "D-T"),bilingual==TRUE), 
       aes(x = rt, fill = shift_type, color=trial_language)) + 
  # geom_histogram() + 
  geom_density(alpha = .5) + 
  facet_wrap(~dataset_name)

ggplot(rts, 
       aes(x = rt)) + 
  geom_histogram() + 
  facet_wrap(~bilingual, scales = "free_y")

ggplot(filter(rts,trial_language=="eng"), 
       aes(x = rt)) + 
  geom_histogram() + 
  facet_wrap(~bilingual, scales = "free_y")

ggplot(filter(rts,trial_language=="eng"), 
       aes(x = rt)) + 
  geom_histogram() + 
  scale_x_log10() + 
  facet_wrap(~bilingual, scales = "free_y")

ggplot(filter(rts,bilingual==TRUE), 
       aes(x = rt, color=trial_language)) + 
  geom_histogram() + 
  scale_x_log10() + 
  facet_wrap(~dataset_name, scales = "free_y")

```

## Subject Averages + Max Exposure 

```{r}
#subject-level averages
rt_average_subj <- rts %>%
  group_by(dataset_name,subject_id,age, bilingual, trial_language) %>%
  filter(rt<=1800, rt>250) %>%
  summarize(
    N = n(),
    average_rt=mean(rt,na.rm=TRUE)
  )


## Sadly, there is no multilingual vanilla data available for the same participant in more than one language :/ 

rt_two_lang <- rt_average_subj %>% filter(bilingual == TRUE) %>% group_by(dataset_name, subject_id, age) %>% summarise(n_langs = n())

rt_average_subj <- rt_average_subj %>% left_join(bilingual_subjects)

ggplot(rt_average_subj,aes(age,average_rt))+
  geom_point()+
  geom_smooth()+
  facet_wrap(~bilingual)

ggplot(filter(rt_average_subj, trial_language == "eng"),aes(age,average_rt))+
  geom_point()+
  geom_smooth(method="lm")+
  facet_wrap(~bilingual)

ggplot(filter(rt_average_subj),aes(age,average_rt))+
  geom_point()+
  geom_smooth(method="lm", aes(color=trial_language)) + facet_wrap(~bilingual)

ggplot(filter(rt_average_subj,bilingual == TRUE, age >= 20, age < 22, trial_language =="eng"),aes(st_exp, average_rt))+
  geom_point()+
  geom_smooth(method="lm")

m <- lmer(average_rt ~st_exp + (1|dataset_name),data=filter(rt_average_subj,bilingual == TRUE, age >= 18, age < 24))
summary(m)
confint(m, method="Wald")

cor_data <- filter(rt_average_subj,bilingual == TRUE, age >= 20, age < 22)

cor(cor_data$average_rt,cor_data$st_exp, use = "complete.obs")

```

```{r}



  ##### summarize by subject by language status ####
# Filter to only english for group comparison, bin ages 
    summarize_by_subj_by_language <- d_joined %>% mutate(age_bin = case_when(
        age < 12 ~ "[0,12)",
        age >= 12 & age < 18 ~ "[12,18)",
        age >= 18 & age < 24 ~ "[18,24)",
        age >= 24 & age < 32 ~ "[24,32)",
        age >= 32 ~ "[32,60]")) %>%
      filter(!is.na(bilingual), trial_language == "eng") %>%
      group_by(administration_id, bilingual, t_norm, age_bin) %>%
      summarize(N = sum(!is.na(correct)), mean_accuracy = mean(correct, na.rm = TRUE))

    #### summarize across subjects ####
    summarize_across_subj_by_language <- summarize_by_subj_by_language %>%
      group_by(bilingual, t_norm, age_bin) %>%
      summarize(
        N = sum(!is.na(mean_accuracy)),
        accuracy = mean(mean_accuracy, na.rm = TRUE),
        sd_accuracy = sd(mean_accuracy, na.rm = TRUE),
        se_accuracy = sd_accuracy / sqrt(N)
      )

      suppressMessages(plot(ggplot(filter(summarize_across_subj_by_language, t_norm > -500 & t_norm <= 2000), aes(x = t_norm, y = accuracy, color = bilingual, group = bilingual)) +
        geom_smooth(data = filter(summarize_by_subj_by_language, t_norm > -500 & t_norm <= 2000), aes(y = mean_accuracy), method = "gam") +
        geom_errorbar(aes(ymin = accuracy - se_accuracy, ymax = accuracy + se_accuracy), width = 0) +
        geom_point() +
        geom_vline(xintercept = 0) +
        geom_vline(xintercept = 300, linetype = "dotted") +
        geom_hline(yintercept = 0.5, linetype = "dashed"))) +facet_wrap(~age_bin)
      
 ## Do the same but group by targets that both monolinguals & multilinguals see
      
      summarize_by_subj_by_language_target <- d_joined %>% mutate(age_bin = case_when(
        age < 12 ~ "[0,12)",
        age >= 12 & age < 18 ~ "[12,18)",
        age >= 18 & age < 24 ~ "[18,24)",
        age >= 24 & age < 32 ~ "[24,32)",
        age >= 32 ~ "[32,60]")) %>%
      filter(!is.na(bilingual), trial_language == "eng") %>%
      group_by(administration_id, bilingual, t_norm, age_bin, target_label) %>%
      summarize(N = sum(!is.na(correct)), mean_accuracy = mean(correct, na.rm = TRUE))
    
    multi_targets <- summarize_by_subj_by_language_target %>% ungroup() %>% filter(bilingual == TRUE) %>% select(target_label) %>% distinct()
    
    summarize_by_subj_by_language_target <- summarize_by_subj_by_language_target %>% filter(target_label %in% multi_targets$target_label)
    
    summarize_across_subj_by_language_target <- summarize_by_subj_by_language_target%>%
      group_by(bilingual, t_norm, age_bin, target_label) %>%
      summarize(
        N = sum(!is.na(mean_accuracy)),
        accuracy = mean(mean_accuracy, na.rm = TRUE),
        sd_accuracy = sd(mean_accuracy, na.rm = TRUE),
        se_accuracy = sd_accuracy / sqrt(N)
      )
      
       suppressMessages(plot(ggplot(filter(summarize_across_subj_by_language_target, t_norm > -500 & t_norm <= 2000), aes(x = t_norm, y = accuracy, color = bilingual, group = bilingual)) +
        geom_smooth(data = filter(summarize_by_subj_by_language_target, t_norm > -500 & t_norm <= 2000), aes(y = mean_accuracy), method = "gam") +
        geom_errorbar(aes(ymin = accuracy - se_accuracy, ymax = accuracy + se_accuracy), width = 0) +
        geom_point() +
        geom_vline(xintercept = 0) +
        geom_vline(xintercept = 300, linetype = "dotted") +
        geom_hline(yintercept = 0.5, linetype = "dashed"))) +facet_wrap(~age_bin + target_label)


```
