---
title: "Reaction times"
author: "Mike Frank"
date: "2022-12-15"
output: html_document
---

```{r}
source(here::here("helper/common.R"))
```


```{r}
trial_ns_acc <- bind_rows(d_summary |>
                            group_by(dataset_name, subject_id) |>
                            count() |>
                            group_by(dataset_name) |>
                            summarise(n = mean(n), 
                                      dimension = "admin"),
                          d_summary |>
                            group_by(dataset_name, target_label) |>
                            count() |>
                            group_by(dataset_name) |>
                            summarise(n = mean(n), 
                                      dimension = "stimulus"))

trial_ns_rt <- bind_rows(d_rt_dt |>
                           group_by(dataset_name, subject_id) |>
                           count() |>
                           group_by(dataset_name) |>
                           summarise(n = mean(n), 
                                     dimension = "admin"),
                         bind_rows(d_rt_dt |>
                                     group_by(dataset_name, subject_id) |>
                                     count() |>
                                     group_by(dataset_name) |>
                                     summarise(n = mean(n), 
                                               dimension = "stimulus")))

acc_rt_iccs <- bind_rows(filter(iccs_long, measure == "acc") |>
                           left_join(trial_ns_acc), 
                         rt_iccs_long |>
                           left_join(trial_ns_rt)) |>
  mutate(dataset_name = fct_reorder(as.factor(dataset_name), icc))


ggplot(acc_rt_iccs, 
       aes(x = dataset_name, y = icc, col = measure)) +
  geom_point(aes(size = n), 
             position = position_dodge(width = .5)) +
  geom_line(aes(group = measure)) + 
  facet_wrap(~dimension) +
  theme(axis.text.x=element_text(angle=-90))

acc_rt_iccs |> 
  arrange(dataset_name) |>
  mutate(icc = round(icc, digits = 2), 
         n = round(n))
```

Let's plot by N. 

```{r}
ggplot(acc_rt_iccs, 
       aes(x = n, y = icc, col = dataset_name)) + 
  geom_point() + 
  geom_smooth(aes(group = 1), method = "loess", span = 10,  se = FALSE) + 
  # scale_x_log10() +
  facet_wrap(dimension~measure, scales = "free_x") + 
  xlab("N trials per child/word") + 
  ylab("Intraclass Correlation Coefficient") + 
  ylim(0,1)

```
This is interesting! We are getting a bunch of signal about individual participants from RT, actually higher ICC than accuracies. Not so much for stimulus information, where it seems like we are doi