---
title: '13: Animacy effects'
author: "Peekbank team"
date: "2025-08-25"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE}
library(here)

source(here("helper/common.R"))
source(here("helper/notebook_helper.R"))
```

# Process d_trial data

```{r}
d_aoi <- readRDS(here("cached_intermediates", "0_d_aoi.rds"))
```

# Load in animate and inanimate data

```{r}
# this existing animacy labels doesn't cover everything we have in the list now
# animacy_labels <- read_csv(here("metadata","animates.csv"))


animates <- c(
  "dog", "cat", "baby", "bird", "cow", "elephant", "lion", "pig", "duck",
  "frog", "zebra", "monkey", "bear", "doggy", "horse", "clown", "fish", "butterfly",
  "giraffe", "chicken", "animal", "boy", "puppy", "lamb", "sheep", "rooster", "tiger", "whale",
  "owl", "caterpillar", "kangaroo", "bunny", "rabbit", "mouse", "goose"
)
questionable <- c("foot", "mouth", "ear", "hand", "eyes", "hair", "leg","nose", "teeth", "belly", "tooth")

all_targets <- d_aoi |>
  distinct(target_label) |>
  rename(item = target_label) |>
  bind_rows(d_aoi |> distinct(distractor_label) |> rename(item = distractor_label)) |>
  distinct(item) |>
  mutate(animate = case_when(
    item %in% animates ~ "yes",
    item %in% questionable ~ "yes", # we can decide about body parts later
    T ~ "no"
  ))

```


```{r}
d_aoi_labelled <- d_aoi |>
  left_join(all_targets, by = c("target_label" = "item")) |>
  rename(animate_target = animate) |>
  left_join(all_targets, by = c("distractor_label" = "item")) |>
  rename(animate_distractor = animate) |> 
  mutate(mixed=animate_distractor!=animate_target)
```

# Time course

overall

```{r}
d_aoi_labelled |>
  group_by(animate_target, animate_distractor, administration_id, t_norm, dataset_name) |>
  summarize(acc = mean(correct, na.rm = T)) |>
  group_by(animate_target, animate_distractor, t_norm, dataset_name) |>
  summarize(acc = mean(acc, na.rm = T)) |>
  ggplot(aes(x = t_norm, y = acc, color = interaction(animate_target, animate_distractor))) +
  geom_line() +
  geom_hline(yintercept = .5, lty = "dashed") +
  geom_vline(xintercept = 0, lty = "dashed") +
      geom_vline(xintercept = 500, lty = "dashed") +
  facet_wrap(~dataset_name) +
  theme(legend.position = "bottom")
```


```{r}
d_aoi_summ <- d_aoi_labelled |>filter(t_norm>-1000) |> 
  group_by(animate_target, animate_distractor, t_norm) |>
  summarize(acc = mean(correct, na.rm = T),
            se= sd(correct, na.rm=T)/sqrt(sum(!is.na(correct))))

d_aoi_summ |> mutate(lower=acc-1.96*se, upper=acc+1.96*se) |> 
  ggplot(aes(x = t_norm, y = acc, ymin=lower, ymax=upper, color = interaction(animate_target, animate_distractor))) +
  geom_line()+
  geom_linerange()+
  #geom_ribbon() +
  geom_hline(yintercept = .5, lty = "dashed") +
  geom_vline(xintercept = 0, lty = "dashed") +
      geom_vline(xintercept = 500, lty = "dashed") +
  theme(legend.position = "bottom")
```

```{r}
d_aoi_summ <- d_aoi_labelled |>filter(t_norm>-1000) |> 
  group_by(animate_target, animate_distractor, t_norm) |>
  summarize(acc = mean_cl_boot(correct))

d_aoi_summ |> mutate(lower=acc-1.96*se, upper=acc+1.96*se) |> 
  ggplot(aes(x = t_norm, y = acc, ymin=lower, ymax=upper, color = interaction(animate_target, animate_distractor))) +
  geom_line()+
  geom_linerange()+
  #geom_ribbon() +
  geom_hline(yintercept = .5, lty = "dashed") +
  geom_vline(xintercept = 0, lty = "dashed") +
      geom_vline(xintercept = 500, lty = "dashed") +
  theme(legend.position = "bottom")
```

```{r}
d_aoi_summ_age <- d_aoi_labelled |>filter(t_norm>-1000) |> make_age_bins() |> 
  group_by(animate_target, animate_distractor, t_norm, age_bin) |>
  summarize(acc = mean(correct, na.rm = T),
            se= sd(correct, na.rm=T)/sqrt(sum(!is.na(correct))))

d_aoi_summ_age |> mutate(lower=acc-1.96*se, upper=acc+1.96*se) |> 
  ggplot(aes(x = t_norm, y = acc, ymin=lower, ymax=upper, color = interaction(animate_target, animate_distractor))) +
  geom_line()+
  geom_linerange()+
  #geom_ribbon() +
  geom_hline(yintercept = .5, lty = "dashed") +
  geom_vline(xintercept = 0, lty = "dashed") +
      geom_vline(xintercept = 500, lty = "dashed") +
  theme(legend.position = "bottom")+facet_wrap(~age_bin)
```