---
title: "9 correlation between RT and accuracy"
output: html_document
date: "2024-08-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
library(tidyverse)
library(here)
theme_set(theme_bw())

acc_start <- 300
acc_end <- 4000
rt_start <- 300
```

# Read stuff

```{r}
load(here("cached_intermediates/1_d_trial.Rds"))

```

# Calculate accuracy and RT for everything

Note, as accuracy best practices develop, may want to do different windowing.

```{r}
acc <- d_trial |>
  group_by(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id) |>
  filter(t_norm >= acc_start) |>
  filter(t_norm <= acc_end) |>
  filter(!is.na(correct)) |>
  summarize(acc = mean(correct))

target_t0 <- d_trial |>
  group_by(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id) |>
  filter(t_norm == rt_start) |>
  rename(aoi_t0 = aoi) |>
  select(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id, aoi_t0)

RT <- d_trial |>
  group_by(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id) |>
  filter(t_norm > rt_start) |>
  group_by(dataset_name, subject_id, administration_id, trial_id, trial_order, dataset_id) |>
  filter(aoi == "target") |>
  summarize(RT = min(t_norm)) |>
  left_join(target_t0)

joint <- acc |> full_join(RT)
```


# Attempt 1 -- ignore for now
## ceiling - acc to RT on same trial  

This is trials RT versus the *same* trials accuracy (ceiling on correlation)

```{r}
do_cor <- function(thing1,thing2){
  if (length(thing1)<2) {NA}
  else {cor.test(thing1, thing2, method = "spearman")$estimate}
}

summ_ceiling <- joint |>
  filter(aoi_t0 != "target") |>
  group_by(dataset_name, administration_id) |>
  summarise(cor = do_cor(acc,RT))

summ_ceiling|> filter(!is.na(cor)) |> ggplot(aes(x=reorder(dataset_name, cor, mean), y=cor))+geom_point(alpha=.05, color="blue")+stat_summary(fun.data="mean_cl_boot")+  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1))+geom_hline(yintercept=0)+labs(y="corr acc-RT same trial", x="dataset")
```

```{r}

paired <- joint |>
  group_by(dataset_name, subject_id, administration_id) |>
  mutate(
    order = row_number(),
    lag_acc = lag(acc),
    lag_RT = lag(RT),
    lag_aoi_t0 = lag(aoi_t0)
  ) |>
  filter(order %% 2 == 0)
```

## ceiling RT-RT adj

```{r}
rt_rt <- paired |> filter(aoi_t0!="target") |> filter(lag_aoi_t0!="target") |> 
  group_by(dataset_name, administration_id) |> 
    summarise(cor = do_cor(lag_RT,RT))
  

rt_rt|> filter(!is.na(cor)) |> ggplot(aes(x=reorder(dataset_name, cor, mean), y=cor))+geom_point(alpha=.05, color="blue")+stat_summary(fun.data="mean_cl_boot")+  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1))+geom_hline(yintercept=0)+labs(y="corr RT-RT adj trial", x="dataset")
```


## ceiling acc - acc adj

```{r}
acc_acc <- paired |> filter(aoi_t0!="target") |> filter(lag_aoi_t0!="target") |> 
  group_by(dataset_name, administration_id) |> 
    summarise(cor = do_cor(acc,lag_acc))
  

acc_acc|> filter(!is.na(cor)) |> ggplot(aes(x=reorder(dataset_name, cor, mean), y=cor))+geom_point(alpha=.05, color="blue")+stat_summary(fun.data="mean_cl_boot")+  theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1))+geom_hline(yintercept=0)+labs(y="corr RT-RT adj trial", x="dataset")
```

## adjacent trials

```{r}


RT_then_acc <- paired |>
  select(dataset_name, subject_id, administration_id,
    RT = lag_RT, aoi_t0 = lag_aoi_t0, acc
  ) |>
  filter(aoi_t0 != "target")

acc_then_RT <- paired |>
  select(dataset_name, subject_id, administration_id,
    RT, aoi_t0,
    acc = lag_acc
  ) |>
  filter(aoi_t0 != "target")

bind_rows(RT_then_acc, acc_then_RT) |>
  group_by(dataset_name) |>
  summarise(cor = cor.test(acc, RT, method = "spearman")$estimate)

bind_rows(RT_then_acc, acc_then_RT) |> ggplot(aes(x = RT, y = acc)) +
  facet_wrap(~dataset_name) +
  geom_point(alpha = .01) +
  geom_smooth(method = "lm")
```
## compare the two

```{r}
both_cors <- bind_rows(RT_then_acc, acc_then_RT) |>
  group_by(dataset_name) |>
  mutate(type = "crossed") |>
  bind_rows(joint |> filter(aoi_t0 != "target") |> group_by(dataset_name) |> mutate(type = "same")) |>
  group_by(dataset_name, type) |>
  summarise(cor = cor.test(acc, RT, method = "spearman")$estimate) |> 
  pivot_wider(names_from=type, values_from=cor)

both_cors

ggplot(both_cors, aes(x=same, y=crossed))+geom_point()+geom_smooth()
```
```{r}

bind_rows(RT_then_acc, acc_then_RT) |> mutate(type = "crossed") |> bind_rows(joint |> filter(aoi_t0 != "target") |> mutate(type="same")) |> ggplot(aes(x = RT, y = acc, color=type)) +
  facet_wrap(~dataset_name) +
  geom_point(alpha = .01) +
  geom_smooth(method = "lm")

```

# Attempt 2

```{r}
halves <- joint |> group_by(administration_id, dataset_name, dataset_id, subject_id) |> mutate(row=row_number(), is_even=ifelse(row%%2==0, "even", "odd"), RT=ifelse(aoi_t0=="target", NA, RT)) |> 
  group_by(is_even, administration_id, dataset_name, dataset_id, subject_id) |> summarize(acc=mean(acc, na.rm=T), RT=mean(RT, na.rm=T)) |> 
  pivot_wider( names_from="is_even", values_from=c("acc","RT"))


do_cor <- function(thing1,thing2){
  if (length(thing1)<2) {NA}
  else {cor.test(thing1, thing2, method = "spearman")$estimate}
}


post_cor <- halves |> group_by(dataset_name, dataset_id) |> 
  summarize(acc_even_acc_odd = do_cor(acc_even, acc_odd),
            rt_even_rt_odd = do_cor(RT_even, RT_odd),
            acc_even_rt_odd = do_cor(acc_even, RT_odd),
            acc_even_rt_even = do_cor(acc_even, RT_even),
            acc_odd_rt_even = do_cor(acc_odd, RT_even), 
            acc_odd_rt_odd = do_cor(acc_odd, RT_odd)) |> 
  filter(!is.na(acc_even_acc_odd))

```
```{r}
ggplot(post_cor, aes(x=acc_even_acc_odd, y=rt_even_rt_odd))+geom_point()+geom_smooth(method="lm")+geom_abline()

post_cor |> select(-acc_even_acc_odd, -rt_even_rt_odd) |> pivot_longer(starts_with("acc")) |> ggplot( aes(x=reorder(dataset_name, value,mean), y=value, color=name))+geom_point()+theme(axis.text.x=element_text(angle=45, vjust=1, hjust=1))+geom_hline(yintercept=0)
```
