---
title: "Order effects"
author: "Hackathon"
date: "2024-08-27"
output: html_document
---

Goal: understand order effects. 


```{r}
source(here::here("helper/common.R"))
```


From prior analysis (`peekbank-analysis`)

```{r}
d_trial_summary <- d_trial %>%
  group_by(dataset_id, dataset_name, administration_id, trial_id, trial_order, 
           age, target_id, target_label, distractor_label) %>%
  summarise(pre_accuracy = mean(correct[t_norm <= 200], na.rm = TRUE),
            post_accuracy = mean(correct[t_norm > 200], na.rm = TRUE)) |>
  filter(!is.na(post_accuracy))

d_trial_summary <- d_trial_summary %>%
  # we put in stimulus pair alphabetically because it needs to be in a consistent order
  # so that we can group by the pairing and not by pairing x target
  mutate(stimulus_pair = paste(c(target_label, distractor_label), collapse = "_")) %>% 
  arrange(dataset_id, administration_id, trial_order) %>%
  group_by(dataset_id, administration_id, stimulus_pair) %>%
  mutate(stimulus_pair_instance = seq(1,n())) %>% # instance is how many times you've seen this pair of stimuli
  ungroup() %>%
  group_by(dataset_id, administration_id, stimulus_pair, target_label) %>%
  #mutate(stimulus_pair_target_instance = seq(1,n())) %>% # target instance is how many times you've seen this pair of stimuli with this target as a target
  ungroup()
```

Remove datasets with fewer than 4 repetitions. 

```{r}
stim_pair_maxes <- d_trial_summary |>
  group_by(dataset_id) |>
  summarise(max_stim_pair_instance = max(stimulus_pair_instance)) |>
  filter(max_stim_pair_instance >= 4)
            
d_stim_pair <- filter(d_trial_summary, dataset_id %in% stim_pair_maxes$dataset_id)
```


```{r}
ggplot(d_stim_pair, aes(x = stimulus_pair_instance)) + 
  geom_histogram() + 
  facet_wrap(~dataset_name)
```
Now look at accuracy within these. 

```{r}
d_stim_pair |>
  group_by(dataset_name, is_first_stimulus, stimulus_pair_target_instance) |>
  summarise(post_accuracy = mean(post_accuracy)) |>
  ggplot(aes(x = stimulus_pair_target_instance, y = post_accuracy, col = is_first_stimulus)) + 
  geom_line() +
  facet_wrap(~dataset_name)
```




----- PRIOR MATERIALS --- 

```{r}
rep_timecourse %>% group_by(dataset_name, stimulus_pair_instance, trial_id) %>% summarize(n = n()) %>% group_by(dataset_name, stimulus_pair_instance) %>% summarise(n = n())
```


```{r boxplot}
# box plot of second time you see this stim pair -- looking to T vs D
d_trial_summary %>%
  filter(target_instance < 3, instance == 2) %>%
  ggplot(aes(x = as.factor(target_instance), y = post_accuracy)) +
  geom_boxplot()
```



```{r}

# number of kids per instance by dataset will help us find datasets that have
# repetition by-design vs by-chance or error
kids_per_instance_table = d_trial_summary %>%
  

  distinct(dataset_name, stimulus_pair_instance, administration_id) %>% 
  

  group_by(dataset_name, stimulus_pair_instance) %>% 
  summarise(n = n()) %>% 
  group_by(dataset_name) %>% 
  mutate(total = sum(n)) %>% 
  ungroup()

# Stacked barplot with proportions

kids_per_instance_table %>% 

  ggplot(aes(x = dataset_name, y = n/total, fill = (stimulus_pair_instance)))+
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "top")+
  coord_flip()


# filtered stacked barplot with proportions

kids_per_instance_table %>% 
    mutate(max_instances = max(stimulus_pair_instance),.by = c("dataset_name")) %>% 
  filter( max_instances > 2) %>% 
  filter( max_instances <5) %>% 
    filter(dataset_name != "baumgartner_2014") %>% 
  filter(dataset_name != "swingley_aslin_2002") %>% 
  ggplot(aes(x = dataset_name, y = n/total, fill = (stimulus_pair_instance)))+
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "top")+
  coord_flip()




d_trial_summary %>% group_by(dataset_name) %>% 
  summarize(n_kids = n_distinct(administration_id))
  

```

# Wonder if age of children in each studies is comparable.

```{r}


d_trial_summary %>% 
  distinct(dataset_name, administration_id,  age) %>% 
  

  group_by(dataset_name, age) %>% 
  summarise(n = n()) %>% 
  group_by(dataset_name) %>% 
  mutate(total = sum(n)) %>% 

  ggplot(aes(x = dataset_name, y = n/total, fill = (age)))+
  geom_bar(stat = "identity", position = "stack") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        legend.position = "top")+
  coord_flip()




```


Maybe we should focus in studies with 3 or more stimulus pair repetitions and less than 5


```{r}



# Keep only "valid" datasets

rep_valid = d_trial_summary %>% 
  filter(dataset_name != "baumgartner_2014") %>% 
  filter(dataset_name != "swingley_aslin_2002")

# get trials that have more than one instance and less than 5
rep_trials <- rep_valid %>%
  group_by(dataset_id, administration_id, stimulus_pair) %>%
  mutate(max_instances = max(stimulus_pair_instance)) %>% 
  ungroup() %>%
  filter(max_instances > 2) %>% 
  filter(max_instances < 5)

# get datasets with repeated trials
rep_datasets <- rep_trials %>%
  distinct(dataset_id)

# just the second time seeing this stimulus pair
rep_timecourse <- d_trial %>%
  left_join(rep_trials) %>% 
  filter(max_instances > 1)




# do you look more to target after having seen this target as a target in this stimulus pair before?
rep_timecourse %>%
  group_by(stimulus_pair_instance, t_norm) %>%
  summarize(accuracy = mean(correct, na.rm=TRUE)) %>%
  filter(t_norm > -3000, t_norm < 4000) %>%
  ggplot(aes(x = t_norm, y = accuracy, color = as.factor(stimulus_pair_instance))) + 
  geom_smooth(method="gam")+
  geom_vline(xintercept=0)+
  geom_hline(yintercept=0.5,linetype="dashed")# +
  #facet_wrap(~stimulus_pair_instance)

# The same as the previous, faceted by study

rep_timecourse %>%
  group_by(stimulus_pair_instance, t_norm,dataset_name) %>%
  summarize(accuracy = mean(correct, na.rm=TRUE)) %>%
  filter(t_norm > -3000, t_norm < 4000) %>%
  ggplot(aes(x = t_norm, y = accuracy, color = as.factor(stimulus_pair_instance))) + 
  geom_smooth(method="gam")+
  geom_vline(xintercept=0)+
  geom_hline(yintercept=0.5,linetype="dashed")+
  facet_wrap(~dataset_name)+
  theme(legend.position = "bottom")



# do you look more to target after having seen this target as a target in this stimulus pair before? faceted by age
# rep_timecourse %>%
#   mutate(age_bin = cut(age, breaks = 4)) %>%
#   group_by(age_bin, stimulus_pair_instance, t_norm) %>%
#   summarize(accuracy = mean(correct, na.rm=TRUE)) %>%
#   filter(t_norm > -2000, t_norm < 4000) %>%
#   ggplot(aes(x = t_norm, y = accuracy, color = as.factor(stimulus_pair_instance)), group = age_bin) + 
#   geom_smooth(method="gam")+
#   facet_wrap(~age_bin) +
#   geom_vline(xintercept=0)+
#   geom_hline(yintercept=0.5,linetype="dashed")

# get all the repeated stimulus pairs (up to 5 repeats)
# rep_timecourse <- d_trial %>%
#   filter(trial_id %in% rep_trials$trial_id) %>%
#   left_join(rep_trials) %>%
#   filter(instance < 5, max_instances > 1)
  
# how does looking change depending on # times you've seen this target as a target in this stim pair?
# rep_timecourse %>%
#   group_by(instance, target_instance, t_norm) %>%
#   summarize(accuracy = mean(correct, na.rm=TRUE), weight = n()) %>% 
#   ungroup() %>%
#   filter(weight > 100) %>%
#   filter(t_norm > -2000, t_norm < 4000) %>%
#   ggplot(aes(x = t_norm, y = accuracy, color = as.factor(target_instance))) + 
#   geom_point(aes(size = log(weight)), shape = 21, alpha = 0.4, fill = NA) +
#   geom_smooth(method="gam", aes(weight = weight, fill = as.factor(target_instance))) +
#   facet_wrap(~instance) +
#   geom_vline(xintercept=0)+
#   geom_hline(yintercept=0.5,linetype="dashed") +
#   theme_bw()

```




```{r}
d_repeated_datasets <- d_trial_summary %>% 


d_trial_summary %>% 
  group_by(stimulus_pair_instance, dataset_name) %>% 
  summarize(mean_accuracy = mean(post_accuracy, na.rm = T)) %>% 
  ggplot(aes(x = stimulus_pair_instance, y = mean_accuracy)) +
  geom_point() +
  facet_wrap(~dataset_name) +
  theme_minimal()
```
